apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: nginx:1.21.6
    volumeMounts:
    - name: mypvc # Must match the volume name defined in the 'volumes' section
      mountPath: "/var/app/config" # The path inside the container where data will be stored
  volumes:
  - name: mypvc 
    persistentVolumeClaim:
      claimName: pvc

