apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:1.21.6
    name: nginx
    volumeMounts:
    - mountPath: /var/run
      name: nginx-run
    - mountPath: /var/cache/nginx
      name: nginx-cache
    - mountPath: /usr/local/nginx
      name: nginx-data
  volumes:
  - name: nginx-run
    emptyDir: {}
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-data
    emptyDir: {}
