apiVersion: batch/v1
kind: Job
metadata:
  name: random-hash
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: random-hash
    spec:
      restartPolicy: Never
      containers:
      - name: random-hash
        image: alpine:3.17.3
        command: ["/bin/sh", "-c"]
        args:
          - echo $RANDOM | base64 | head -c 20

